# database generated on 2024-11-08 17:37 GMT
!!omap
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/div-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - div
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/divu-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - divu
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/mul-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - mul
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/mulh-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - mulh
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/mulhsu-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - mulhsu
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/mulhu-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - mulhu
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/rem-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - rem
- /home/user/Work/New_Repo/riscv-arch-test-PR/riscv-test-suite/rv32i_m/M/src/remu-01.S:
    commit_id: '-'
    isa:
    - RV32IM
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*M.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - remu
