// --------------------------------------------------------------------------------
// Copyright (C) 2025 Harvey Mudd College & Oklahoma State University, UET Lahore, Habib University
// SPDX-License-Identifier: Apache-2.0
//
// Title        : Comprehensive PMP (Physical Memory Protection) Verification
// Authors      : Umer Shahid, Allen Baum, David Harris
//                Muhammad Abdullah, Hamza Ali, Muhammad Zain
//
// Description : This test verifies the functionality and enforcement of
//               Physical Memory Protection (PMP) configurations in RISC-V
//               systems. It specifically tests the Read, Write, and Execute
//               permissions for a designated memory region, ensuring that
//               the PMP settings are correctly applied and that the system
//               behaves as expected when accessing this region.
//
// Coverpoints : cp_cfg_L_access_all & cp_none for PMPM are fully covered in
//               this test file.
//
// Test Cases  : Checking M-mode access when all PMP are off. Checking that XWR
//               doesn't affect M-mode access when L=0. Setting (PMP_writable_regs-1)
//               as standard PMP regions, with pmp.L = 0, pmp.A=NAPOT, pmp.XWR = 0
//               {jalr, lw, sw} in each PMP region. Access should always succeed
//               because L=0 doesn't enforce permissions.
// --------------------------------------------------------------------------------

##### START_TEST_CONFIG #####
# REQUIRED_EXTENSIONS:  ['Sm']
# params:
#   MXLEN: 32
#   NUM_PMP_ENTRIES: '>0'
# MARCH: rv32i_zicsr_zifencei
##### END_TEST_CONFIG #####

// Define the size of the signature region
#define SIGUPD_COUNT 50




// Include framework macros
#include "riscv_arch_test.h"

// Set up test environment and declare main entry point
RVTEST_BEGIN

.macro VERIFICATION_RWX ADDRESS, TEST_CASE      // {jalr, sw, lw} at start of region (0x80002000)
    // Execution Access Check
    LA (a4, \ADDRESS)
    LA(x1, 1f)                            // Store the return Address in x1
    RVTEST_FENCEI                              // sync I-cache: a prior store may have updated this executable region
    jalr ra, 0(a4)
    nop
    nop
1:
    nop
    nop

    // Store Access Check
    LA(a5, \ADDRESS)                        // Address to be verified
    LI(a4, NOP)                                // Value to write (NOP)
    \TEST_CASE\()_2:
    sw a4, 0(a5)                            // Word store test
    nop
    RVTEST_SIGUPD(x2, x5, x4, a4, \TEST_CASE\()_2, test_2_str)

    // Load Access Check
    \TEST_CASE\()_1:
    lw a4, 0(a5)                            // Word load test
    nop
    RVTEST_SIGUPD(x2, x5, x4, a4, \TEST_CASE\()_1, test_1_str)     // Signature update

.endm

main:
    // Loop to SET ALL pmpcfg REGs to zero
    .set pmpcfgi, CSR_PMPCFG0
    .rept UDB_NUM_PMP_ENTRIES/4
    csrw pmpcfgi , x0
    .set pmpcfgi, pmpcfgi+1
    .endr

    // Loop to SET ALL pmpaddr REGs to zero
    .set pmpaddri, CSR_PMPADDR0
    .rept UDB_NUM_PMP_ENTRIES
    csrw pmpaddri, x0
    .set pmpaddri, pmpaddri+1
    .endr

//                                          Verification Section
// Test Case: 0 -- M-mode access succeeds when all PMP are off

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_0
    RVTEST_GOTO_MMODE

#define PMPREGION_XWR_000   ((                        PMP_NAPOT)&0xFF)

#define REGIONSTART         TEST_FOR_EXECUTION
#if UDB_PMP_GRANULARITY != 2
    #define PMP_MASK            ~((1 << (UDB_PMP_GRANULARITY - 3))-1)
    #define PMP_REGION_SIZE     (1 << (UDB_PMP_GRANULARITY - 3)) - 1
#else
    #define PMP_MASK            ~0
    #define PMP_REGION_SIZE     0
#endif


    RVTEST_PMP_SET_BACKGROUND x4

//                                          Verification Section
// Test Case: 1 : L -> 0 and No Permissions given to the PMP Region 14

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr14, x5

    LI(x4, (PMPREGION_XWR_000 << PMP2_CFG_SHIFT))
    csrw pmpcfg3, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_1

// Test Case: 2 : L -> 0 and No Permissions given to the PMP Region 13

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr13, x5

    LI(x4, (PMPREGION_XWR_000 << PMP1_CFG_SHIFT))
    csrw pmpcfg3, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_2

// Test Case: 3 : L -> 0 and No Permissions given to the PMP Region 12

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr12, x5

    LI(x4, (PMPREGION_XWR_000 << PMP0_CFG_SHIFT))
    csrw pmpcfg3, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_3

// Test Case: 4 : L -> 0 and No Permissions given to the PMP Region 11

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr11, x5

    LI(x4, (PMPREGION_XWR_000 << PMP3_CFG_SHIFT))
    csrw pmpcfg2, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_4

// Test Case: 5 : L -> 0 and No Permissions given to the PMP Region 10

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr10, x5

    LI(x4, (PMPREGION_XWR_000 << PMP2_CFG_SHIFT))
    csrw pmpcfg2, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_5

// Test Case: 6 : L -> 0 and No Permissions given to the PMP Region 9

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr9, x5

    LI(x4, (PMPREGION_XWR_000 << PMP1_CFG_SHIFT))
    csrw pmpcfg2, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_6


// Test Case: 7 : L -> 0 and No Permissions given to the PMP Region 8

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr8, x5

    LI(x4, (PMPREGION_XWR_000 << PMP0_CFG_SHIFT))
    csrw pmpcfg2, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_7

// Test Case: 8 : L -> 0 and No Permissions given to the PMP Region 7

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr7, x5

    LI(x4, (PMPREGION_XWR_000 << PMP3_CFG_SHIFT))
    csrw pmpcfg1, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_8

// Test Case: 9 : L -> 0 and No Permissions given to the PMP Region 6

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr6, x5

    LI(x4, (PMPREGION_XWR_000 << PMP2_CFG_SHIFT))
    csrw pmpcfg1, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_9

// Test Case: 10 : L -> 0 and No Permissions given to the PMP Region 5

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr5, x5

    LI(x4, (PMPREGION_XWR_000 << PMP1_CFG_SHIFT))
    csrw pmpcfg1, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_10

// Test Case: 11 : L -> 0 and No Permissions given to the PMP Region 4

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr4, x5

    LI(x4, (PMPREGION_XWR_000 << PMP0_CFG_SHIFT))
    csrw pmpcfg1, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_11

// Test Case: 12 : L -> 0 and No Permissions given to the PMP Region 3

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr3, x5

    LI(x4, (PMPREGION_XWR_000 << PMP3_CFG_SHIFT))
    csrw pmpcfg0, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_12

// Test Case: 13 : L -> 0 and No Permissions given to the PMP Region 2

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr2, x5

    LI(x4, (PMPREGION_XWR_000 << PMP2_CFG_SHIFT))
    csrw pmpcfg0, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_13

// Test Case: 14 : L -> 0 and No Permissions given to the PMP Region 1

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr1, x5

    LI(x4, (PMPREGION_XWR_000 << PMP1_CFG_SHIFT))
    csrw pmpcfg0, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_14

// Test Case: 15 : L -> 0 and No Permissions given to the PMP Region 0

    LA(x5, TEST_FOR_EXECUTION)
    srl x5, x5, PMP_SHIFT
    LI(x6,PMP_MASK)
    and x5, x5, x6
    LI(x6,PMP_REGION_SIZE)
    or x5, x5, x6
    csrw pmpaddr0, x5

    LI(x4, (PMPREGION_XWR_000 << PMP0_CFG_SHIFT))
    csrw pmpcfg0, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_15

RVTEST_CODE_END
RVTEST_DATA_BEGIN

// Test case strings for reporting
test_1_str: .string "\"test: 1; cp: cp_cfg_L_access_all_lw and cp_none_lw\""
test_2_str: .string "\"test: 2; cp: cp_cfg_L_access_all_sw and cp_none_sw\""

.p2align 12
TEST_FOR_EXECUTION_0:
    .rept PMP_NAPOT_REGION_PAD_WORDS   // g_napot-byte pad -> NAPOT region-under-test at 0x80005008 (PMP_NAPOT_REGION_START); pmpaddr matches STANDARD_REGION, region does not cover the pad
    jr ra
    .endr

TEST_FOR_EXECUTION:
    .rept (1<<(UDB_PMP_GRANULARITY))
    nop
    .endr

RETURN_INSTRUCTION:
    nop
    nop
    jr ra                                                        // Get back to the point from where TEST_FOR_EXECUTION was called.

RVTEST_DATA_END

// Signature region for self-checking
RVTEST_SIG_SETUP
