// --------------------------------------------------------------------------------
// Copyright (C) 2025 Harvey Mudd College & Oklahoma State University, UET Lahore, Habib University
// SPDX-License-Identifier: Apache-2.0
//
// Title        : Comprehensive PMP (Physical Memory Protection) Verification
// Authors      : Umer Shahid, Allen Baum, David Harris
//                Muhammad Abdullah, Hamza Ali, Muhammad Zain
//
// Description : This test verifies the functionality and enforcement of
//               Physical Memory Protection (PMP) configurations in RISC-V
//               systems. It specifically tests the Read, Write, and Execute
//               permissions for a designated memory region, ensuring that
//               the PMP settings are correctly applied and that the system
//               behaves as expected when accessing this region.
//
// Coverpoints: cp_grain for PMPM is fully covered in this test file.
//
// Test case  : Checking that low bits read as 0/1s depending on grain and address
//              matching mode. Set up pmpcfg0.L = 0, pmpcfg.A = {OFF/NAPOT}, write
//              pmpaddr0 = {all 0s / all 1s / checkerboard}. Change pmpcfg.A to
//              {OFF/TOR/NAPOT} and read back pmpaddr0. Bottom G-1 bits always read
//              as 1s in NAPOT. Bottom G bits read as 0s in TOR/OFF.
// --------------------------------------------------------------------------------


##### START_TEST_CONFIG #####
# REQUIRED_EXTENSIONS:  ['Sm']
# params:
#   MXLEN: 32
#   NUM_PMP_ENTRIES: '>0'
# MARCH: rv32i_zicsr_zifencei
##### END_TEST_CONFIG #####

// Define the size of the signature region
#define SIGUPD_COUNT 50


// Include framework macros
#include "riscv_arch_test.h"

// Set up test environment and declare main entry point
RVTEST_BEGIN

main:
    // Loop to SET ALL pmpcfg REGs to zero
    .set pmpcfgi, CSR_PMPCFG0
    .rept UDB_NUM_PMP_ENTRIES/4
    csrw pmpcfgi , x0
    .set pmpcfgi, pmpcfgi+1
    .endr

    // Loop to SET ALL pmpaddr REGs to zero
    .set pmpaddri, CSR_PMPADDR0
    .rept UDB_NUM_PMP_ENTRIES
    csrw pmpaddri, x0
    .set pmpaddri, pmpaddri+1
    .endr

#define PMPREGION_OFF       ((((     PMP_R|PMP_W|PMP_X)            &0xFF) << PMP0_CFG_SHIFT))
#define PMPREGION_NAPOT     ((((     PMP_R|PMP_W|PMP_X |PMP_NAPOT) &0xFF) << PMP0_CFG_SHIFT))
#define PMPREGION_TOR       ((((     PMP_R|PMP_W|PMP_X |PMP_TOR)   &0xFF) << PMP0_CFG_SHIFT))

#define REGIONSTART         TEST_FOR_EXECUTION

    RVTEST_PMP_SET_BACKGROUND x4

    LA(x4, REGIONSTART)
    srl x4, x4, PMP_SHIFT
    csrw pmpaddr0, x4
                                                //Verification Section
// Test Case 1: Writing all 0s in pmpaddr0 when A = NAPOT and read back when A= {OFF,NAPOT,TOR}

// Write all 0s in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, 0)
    csrw pmpaddr0, x6

// Read back in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    test_1:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_1, test_1_str)


// Write all 0s in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, 0)
    csrw pmpaddr0, x6

// Read back in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    test_2:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_2, test_2_str)

#ifdef UDB_PMP_TOR_SUPPORTED

// Write all 0s in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, 0)
    csrw pmpaddr0, x6

// Read back in  TOR

    LI(x6, PMPREGION_TOR)
    csrw pmpcfg0, x6
    test_3:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_3, test_3_str)

#endif

// Test Case 2: Writing all 0s in pmpaddr0 when A = OFF and read back when A= {OFF,NAPOT,TOR}

// Write all 0s in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, 0)
    csrw pmpaddr0, x6

// Read back in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    test_4:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_4, test_4_str)

// Write all 0s in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, 0)
    csrw pmpaddr0, x6

// Read back in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    test_5:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_5, test_5_str)

#ifdef UDB_PMP_TOR_SUPPORTED

// Write all 0s in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, 0)
    csrw pmpaddr0, x6

// Read back in TOR

    LI(x6, PMPREGION_TOR)
    csrw pmpcfg0, x6
    test_6:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_6, test_6_str)

#endif

// Test Case 3: Writing all 1s in pmpaddr0 when A = NAPOT and read back when A= {OFF,NAPOT,TOR}

// Write all 1s in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, -1)
    csrw pmpaddr0, x6

// Read back in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    test_7:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_7, test_7_str)

// Write all 1s in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, -1)
    csrw pmpaddr0, x6

// Read back in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    test_8:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_8, test_8_str)

#ifdef UDB_PMP_TOR_SUPPORTED

// Write all 1s in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, -1)
    csrw pmpaddr0, x6

// Read back in TOR

    LI(x6, PMPREGION_TOR)
    csrw pmpcfg0, x6
    test_9:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_9, test_9_str)

#endif

// Test Case 4: Writing all 1s in pmpaddr0 when A = OFF and read back when A= {OFF,NAPOT,TOR}

// Write all 1s in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, -1)
    csrw pmpaddr0, x6

// Read back in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    test_10:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_10, test_10_str)

// Write all 1s in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, -1)
    csrw pmpaddr0, x6

// Read back in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    test_11:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_11, test_11_str)

#ifdef UDB_PMP_TOR_SUPPORTED

// Write all 1s in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, -1)
    csrw pmpaddr0, x6

// Read back in TOR

    LI(x6, PMPREGION_TOR)
    csrw pmpcfg0, x6
    test_12:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_12, test_12_str)

#endif

// Test Case 5: Writing checkerboard pattern(1010...) in pmpaddr0 when A = NAPOT and read back when A= {OFF,NAPOT,TOR}

// Write checkerboard in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, 0xAAAAAAAA)
    csrw pmpaddr0, x6

// Read back in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    test_13:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_13, test_13_str)

// Write checkerboard in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, 0xAAAAAAAA)
    csrw pmpaddr0, x6

// Read back in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    test_14:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_14, test_14_str)

#ifdef UDB_PMP_TOR_SUPPORTED

// Write checkerboard in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    LI(x6, 0xAAAAAAAA)
    csrw pmpaddr0, x6

// Read back in TOR

    LI(x6, PMPREGION_TOR)
    csrw pmpcfg0, x6
    test_15:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_15, test_15_str)

#endif

// Test Case 6: Writing checkerboard pattern(1010...) in pmpaddr0 when A = OFF and read back when A= {OFF,NAPOT,TOR}

// Write checkerboard in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, 0xAAAAAAAA)
    csrw pmpaddr0, x6

// Read back in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    test_16:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_16, test_16_str)

// Write checkerboard in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, 0xAAAAAAAA)
    csrw pmpaddr0, x6

// Read back in NAPOT

    LI(x6, PMPREGION_NAPOT)
    csrw pmpcfg0, x6
    test_17:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_17, test_17_str)

#ifdef UDB_PMP_TOR_SUPPORTED

// Write checkerboard in OFF

    LI(x6, PMPREGION_OFF)
    csrw pmpcfg0, x6
    LI(x6, 0xAAAAAAAA)
    csrw pmpaddr0, x6

// Read back in TOR

    LI(x6, PMPREGION_TOR)
    csrw pmpcfg0, x6
    test_18:
    RVTEST_SIGUPD_CSR_READ(pmpaddr0, x7, test_18, test_18_str)

#endif

    RVTEST_GOTO_MMODE

RVTEST_CODE_END
RVTEST_DATA_BEGIN
.p2align 4

// Test case strings for reporting
test_1_str:  .string "\"test: 1;  cp: cp_pmp_grain\""
test_2_str:  .string "\"test: 2;  cp: cp_pmp_grain\""
test_3_str:  .string "\"test: 3;  cp: cp_pmp_grain\""
test_4_str:  .string "\"test: 4;  cp: cp_pmp_grain\""
test_5_str:  .string "\"test: 5;  cp: cp_pmp_grain\""
test_6_str:  .string "\"test: 6;  cp: cp_pmp_grain\""
test_7_str:  .string "\"test: 7;  cp: cp_pmp_grain\""
test_8_str:  .string "\"test: 8;  cp: cp_pmp_grain\""
test_9_str:  .string "\"test: 9;  cp: cp_pmp_grain\""
test_10_str: .string "\"test: 10; cp: cp_pmp_grain\""
test_11_str: .string "\"test: 11; cp: cp_pmp_grain\""
test_12_str: .string "\"test: 12; cp: cp_pmp_grain\""
test_13_str: .string "\"test: 13; cp: cp_pmp_grain\""
test_14_str: .string "\"test: 14; cp: cp_pmp_grain\""
test_15_str: .string "\"test: 15; cp: cp_pmp_grain\""
test_16_str: .string "\"test: 16; cp: cp_pmp_grain\""
test_17_str: .string "\"test: 17; cp: cp_pmp_grain\""
test_18_str: .string "\"test: 18; cp: cp_pmp_grain\""

.p2align 12
TEST_FOR_EXECUTION_0:
    .rept (1 << (UDB_PMP_GRANULARITY - 2))              // one PMP granule of jr-ra fillers: puts TEST_FOR_EXECUTION on the next granule boundary (= PMP_REGION_START at coverage grain 2), while staying naturally aligned for NAPOT at larger grains
    jr ra
    .endr

TEST_FOR_EXECUTION:
    .rept (1<<(UDB_PMP_GRANULARITY))
    nop
    .endr

RETURN_INSTRUCTION:
    nop
    nop
    jr ra                                                        // Get back to the point from where TEST_FOR_EXECUTION was called.

RVTEST_DATA_END

// Signature region for self-checking
RVTEST_SIG_SETUP
