repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.0
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter. (disabled until format PR merged)
    # - id: ruff-format
    #   args: [ --check ]