# database generated on 2024-06-03 16:17 GMT
!!omap
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/ebreak.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - ebreak
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/ecall.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - ecall
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-beq-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-beq
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-beq
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-bge-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bge
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bge
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-bgeu-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bgeu
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bgeu
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-blt-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-blt
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-blt
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-bltu-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bltu
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bltu
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-bne-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bne
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-bne
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-jal-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-jal
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-jal
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-lh-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        - check hw_data_misaligned_support:=True
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-lh
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check hw_data_misaligned_support:=False
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-lh
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-lhu-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        - check hw_data_misaligned_support:=True
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-lhu
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check hw_data_misaligned_support:=False
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-lhu
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-lw-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        - check hw_data_misaligned_support:=True
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-lw
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check hw_data_misaligned_support:=False
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-lw
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-sh-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        - check hw_data_misaligned_support:=True
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-sh
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check hw_data_misaligned_support:=False
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-sh
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign-sw-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        - check hw_data_misaligned_support:=True
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-sw
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check hw_data_misaligned_support:=False
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign-sw
- /home/user/Work/Tests/riscv-test-suite/rv32i_m/privilege/src/misalign2-jalr-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*C.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign2-jalr
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        - check ISA:=regex(^[^C]+$)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign2-jalr
