# yaml-language-server: $schema=../../../external/riscv-unified-db/spec/schemas/config_schema.json
---
$schema: config_schema.json#
kind: architecture configuration
type: fully configured
name: imperas-RVI20U64
description: RVI20U64 with all optional extensions
implemented_extensions:
  - { name: I, version: "= 2.1" }
  - { name: M, version: "= 2.0" }
  - { name: A, version: "= 2.1.0" }
  - { name: F, version: "= 2.2.0" }
  - { name: D, version: "= 2.2.0" }
  - { name: C, version: "= 2.0" }
  - { name: Zicntr, version: "= 2.0" }
  #  - { name: Zihpm, version: "= 2.0" }   // haven't found a way to turn this on in imperas.ic in this variant
  - { name: Zicsr, version: "= 2.0" }
  - { name: Zifencei, version: "= 2.0.0" }
  - { name: Zaamo, version: "= 1.0.0" }
  - { name: Zalrsc, version: "= 1.0.0" }
  - { name: Zca, version: "= 1.0.0" }
  - { name: Zcd, version: "= 1.0.0" }
  - { name: Zmmul, version: "= 1.0.0" }
  - { name: Sm, version: "= 1.12.0" }

params:
  # A params
  MISALIGNED_AMO: false
  LRSC_RESERVATION_STRATEGY: "reserve exactly enough to cover the access" # XLEN size reservation
  LRSC_FAIL_ON_VA_SYNONYM: false
  LRSC_MISALIGNED_BEHAVIOR: "always raise access fault"
  LRSC_FAIL_ON_NON_EXACT_LRSC: false
  MUTABLE_MISA_A: false
  # M params
  MUTABLE_MISA_M: false
  # F params
  MUTABLE_MISA_F: false
  HW_MSTATUS_FS_DIRTY_UPDATE: precise
  MSTATUS_FS_LEGAL_VALUES: [0, 1, 2, 3]
  # D params
  MUTABLE_MISA_D: false
  # C params
  MUTABLE_MISA_C: false
  # Zicntr params
  TIME_CSR_IMPLEMENTED: true
  # Sm params
  MXLEN: 64
  PRECISE_SYNCHRONOUS_EXCEPTIONS: true
  TRAP_ON_ECALL_FROM_M: true
  TRAP_ON_EBREAK: true
  MARCHID_IMPLEMENTED: true
  ARCH_ID_VALUE: 0x1
  MIMPID_IMPLEMENTED: true
  IMP_ID_VALUE: 0x0
  VENDOR_ID_BANK: 0x0
  VENDOR_ID_OFFSET: 0x0
  MISALIGNED_LDST: true
  MISALIGNED_LDST_EXCEPTION_PRIORITY: low
  MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE: 4096
  MISALIGNED_SPLIT_STRATEGY: sequential_bytes
  TRAP_ON_ILLEGAL_WLRL: false
  TRAP_ON_UNIMPLEMENTED_INSTRUCTION: true
  TRAP_ON_RESERVED_INSTRUCTION: true
  TRAP_ON_UNIMPLEMENTED_CSR: true
  REPORT_VA_IN_MTVAL_ON_BREAKPOINT: true
  REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT: true
  REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION: true
  MTVAL_WIDTH: 64
  CONFIG_PTR_ADDRESS: 0
  PMA_GRANULARITY: 3
  PHYS_ADDR_WIDTH: 57
  M_MODE_ENDIANNESS: little
  MISA_CSR_IMPLEMENTED: true
  MTVEC_ACCESS: rw
  MTVEC_MODES: [0, 1]
  MTVEC_BASE_ALIGNMENT_DIRECT: 4
  MTVEC_BASE_ALIGNMENT_VECTORED: 4
  MTVEC_ILLEGAL_WRITE_BEHAVIOR: retain
  HPM_COUNTER_EN:
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ]
  MCOUNTINHIBIT_IMPLEMENTED: true
  COUNTINHIBIT_EN:
    [
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ]
  NUM_PMP_ENTRIES: 0
  MCOUNTENABLE_EN:
    [
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ]
