name: spike-rv32g
compiler_exe: riscv64-unknown-elf-gcc # executable name on $PATH or full path to executable
objdump_exe: riscv64-unknown-elf-objdump # executable name on $PATH or full path to executable, optional
ref_model_exe: sail_riscv_sim # executable name on $PATH or full path to executable
udb_config: spike-rv32g.yaml
linker_script: link.ld
dut_include_dir: . # Directory containing DUT-specific config headers (e.g., rvmodel_macros.h, rvtest_config.h)
include_priv_tests: False
