// --------------------------------------------------------------------------------------------------------------------------------
// Developed by: Umer Shahid & Muhammad Zain
// --------------------------------------------------------------------------------------------------------------------------------
// Test cases are as follows:
// --------------------------------------------------------------------------------------------------------------------------------
// Set menvcfg.PBMTE = 1
// --------------------------------------------------------------------------------------------------------------------------------
// 1. Setup a PTE at level 4 with PBMT=1, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 2. Setup a PTE at level 4 with PBMT=2, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 3. Setup a PTE at level 4 with PBMT=3 (reserved encoding), RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: Store, load & fetch page fault
// 4. Setup a PTE at level 3 with PBMT=1, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 5. Setup a PTE at level 3 with PBMT=2, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 6. Setup a PTE at level 3 with PBMT=3 (reserved encoding), RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: Store, load & fetch page fault
// 7. Setup a PTE at level 2 with PBMT=1, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 8. Setup a PTE at level 2 with PBMT=2, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 9. Setup a PTE at level 2 with PBMT=3 (reserved encoding), RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: Store, load & fetch page fault
// 10. Setup a PTE at level 1 with PBMT=1, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 11. Setup a PTE at level 1 with PBMT=2, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 12. Setup a PTE at level 1 with PBMT=3 (reserved encoding), RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: Store, load & fetch page fault
// 13. Setup a PTE at level 0 with PBMT=1, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 14. Setup a PTE at level 0 with PBMT=2, RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: No fault
// 15. Setup a PTE at level 0 with PBMT=3 (reserved encoding), RWX permissions given:
//         Then, in S-Mode, the page is accessed --> required: Store, load & fetch page fault
//
// Total Expected Faults :: 15
// --------------------------------------------------------------------------------------------------------------------------------

##### START_TEST_CONFIG #####
# REQUIRED_EXTENSIONS: [I, Sv57, Svpbmt]
# MARCH: rv64i_zicsr_zifencei
##### END_TEST_CONFIG #####

// TODO: Remove BOOT_TO_MMODE when converting this test to T-SBI.
#define BOOT_TO_MMODE

#define SIGUPD_COUNT 50


#include "riscv_arch_test.h"

RVTEST_BEGIN

//---------------------------------------------------------------------------------------------------------------------------------
// Test RWX permissions
.macro VERIFICATION_RWX TEST_CASE
  addi a2, a2, 16

  // Test store permission
  \TEST_CASE\()_store:
  sw  a2, 20(a5)
  nop

  // Test load permission
  \TEST_CASE\()_load:
  lw a3, 20(a5)
  nop

  // Test execute permission
  \TEST_CASE\()_exec:
  jalr ra, a5, 0
  nop
.endm

.macro TEST_CASES_RUNNER LOWER_MODE, VA, level, TEST_CASE

  // Adjust offset of VA to point to test region
  .set VA_SHIFT, (\level*9)+12
  LI(a5, (\VA>>VA_SHIFT)<<VA_SHIFT)
  LA(a0, rvtest_data_1)
  slli a0, a0, 64-VA_SHIFT
  srli a0, a0, 64-VA_SHIFT
  add  a5, a5, a0             // Virtual Address

  RVTEST_GOTO_LOWER_MODE \LOWER_MODE

  VERIFICATION_RWX \TEST_CASE

  RVTEST_GOTO_MMODE

  // Signature Update
  RVTEST_SIGUPD(x2, x5, x4, a2, \TEST_CASE\()_store, \TEST_CASE\()_store_str)
  RVTEST_SIGUPD(x2, x5, x4, a3, \TEST_CASE\()_load, \TEST_CASE\()_load_str)
  RVTEST_SIGUPD(x2, x5, x4, a4, \TEST_CASE\()_exec, \TEST_CASE\()_exec_str)
.endm


main:
  LI( a2, 0x800)              // Test signature initialization

//---------------------------------------------------------------------------------------------------------------------------------
//                                   Virtual addresses definition for code and test regions
//---------------------------------------------------------------------------------------------------------------------------------

  // Virtual Address of Test section (rvtest_data_1)
  .set va_data,               0x07028500403000

  // Virtual Address for code region
  .set va_rvtest_code_begin,  0x03000080000000


  // PTE setup for Code Region
  SUPERPAGE_PTE_SETUP_SV57(rvtest_code_begin, (PTE_D | PTE_A | PTE_X | PTE_R | PTE_V), va_rvtest_code_begin, LEVEL4)
  sfence.vma

  // Save area setup for code region
  csrr a0, mscratch
  SAVE_AREA_SETUP(va_rvtest_code_begin, rvtest_code_begin, code, LEVEL4)

//---------------------------------------------------------------------------------------------------------------------------------
//                                               Test Cases Start from here
//---------------------------------------------------------------------------------------------------------------------------------

  SATP_SETUP_RV64(sv57)                                                  // Set SATP for virtualization
  sfence.vma                                                             // Flush TLB

  LI(t0, MENVCFG_PBMTE)
  csrs menvcfg, t0                                                      // Enable Svpbmt

//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//                                                    TESTS AT LEVEL 4
//---------------------------------------------------------------------------------------------------------------------------------
//                    256TB PAGE    Region 1 under test at level 4 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 1: Test in S-Mode | RWX bit set | PTE.PBMT=1 | expected = No fault
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((1 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL4)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL4, test1

//---------------------------------------------------------------------------------------------------------------------------------
//                    256TB PAGE    Region 1 under test at level 4 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 2: Test in S-Mode | RWX bit set | PTE.PBMT=2 | expected = No fault
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((2 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL4)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL4, test2

//---------------------------------------------------------------------------------------------------------------------------------
//                    256TB PAGE    Region 1 under test at level 4 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

#ifdef S1P12P0_OR_LATER_SUPPORTED
  // Test case 3: Test in S-Mode | RWX bit set | PTE.PBMT=3 | expected = Store, Load & Instr page faults
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((3 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL4)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL4, test3
#endif


//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//                                                    TESTS AT LEVEL 3
//---------------------------------------------------------------------------------------------------------------------------------
//                    512GB PAGE    Region 1 under test at level 3 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 4: Test in S-Mode | RWX bit set | PTE.PBMT=1 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((1 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL3)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL3, test4

//---------------------------------------------------------------------------------------------------------------------------------
//                    512GB PAGE    Region 1 under test at level 3 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 5: Test in S-Mode | RWX bit set | PTE.PBMT=2 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((2 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL3)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL3, test5

//---------------------------------------------------------------------------------------------------------------------------------
//                    512GB PAGE    Region 1 under test at level 3 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

#ifdef S1P12P0_OR_LATER_SUPPORTED
  // Test case 6: Test in S-Mode | RWX bit set | PTE.PBMT=3 | expected = Store, Load & Instr page faults
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((3 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL3)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL3, test6
#endif


//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//                                                    TESTS AT LEVEL 2
//---------------------------------------------------------------------------------------------------------------------------------
//                    1GB PAGE    Region 1 under test at level 2 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 7: Test in S-Mode | RWX bit set | PTE.PBMT=1 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((1 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL2)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL2, test7

//---------------------------------------------------------------------------------------------------------------------------------
//                    1GB PAGE    Region 1 under test at level 2 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 8: Test in S-Mode | RWX bit set | PTE.PBMT=2 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((2 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL2)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL2, test8

//---------------------------------------------------------------------------------------------------------------------------------
//                    1GB PAGE    Region 1 under test at level 2 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

#ifdef S1P12P0_OR_LATER_SUPPORTED
  // Test case 9: Test in S-Mode | RWX bit set | PTE.PBMT=3 | expected = Store, Load & Instr page faults
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((3 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL2)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL2, test9
#endif


//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//                                                    TESTS AT LEVEL 1
//---------------------------------------------------------------------------------------------------------------------------------
//                    2MB PAGE    Region 1 under test at level 1 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 10: Test in S-Mode | RWX bit set | PTE.PBMT=1 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  PTE_SETUP_SV57(rvtest_slvl1_pg_tbl, (PTE_V), va_data, LEVEL2)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((1 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL1)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL1, test10

//---------------------------------------------------------------------------------------------------------------------------------
//                    2MB PAGE    Region 1 under test at level 1 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 11: Test in S-Mode | RWX bit set | PTE.PBMT=2 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  PTE_SETUP_SV57(rvtest_slvl1_pg_tbl, (PTE_V), va_data, LEVEL2)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((2 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL1)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL1, test11

//---------------------------------------------------------------------------------------------------------------------------------
//                    2MB PAGE    Region 1 under test at level 1 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

#ifdef S1P12P0_OR_LATER_SUPPORTED
  // Test case 12: Test in S-Mode | RWX bit set | PTE.PBMT=3 | expected = Store, Load & Instr page faults
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  PTE_SETUP_SV57(rvtest_slvl1_pg_tbl, (PTE_V), va_data, LEVEL2)
  SUPERPAGE_PTE_SETUP_SV57(rvtest_data_1, ((3 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL1)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL1, test12
#endif


//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//                                                    TESTS AT LEVEL 0
//---------------------------------------------------------------------------------------------------------------------------------
//                    4KB PAGE    Region 1 under test at level 0 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 13: Test in S-Mode | RWX bit set | PTE.PBMT=1 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  PTE_SETUP_SV57(rvtest_slvl1_pg_tbl, (PTE_V), va_data, LEVEL2)
  PTE_SETUP_SV57(rvtest_slvl0_pg_tbl, (PTE_V), va_data, LEVEL1)
  PTE_SETUP_SV57(rvtest_data_1, ((1 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL0)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL0, test13

//---------------------------------------------------------------------------------------------------------------------------------
//                    4KB PAGE    Region 1 under test at level 0 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

  // Test case 14: Test in S-Mode | RWX bit set | PTE.PBMT=2 | expected = No fault
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  PTE_SETUP_SV57(rvtest_slvl1_pg_tbl, (PTE_V), va_data, LEVEL2)
  PTE_SETUP_SV57(rvtest_slvl0_pg_tbl, (PTE_V), va_data, LEVEL1)
  PTE_SETUP_SV57(rvtest_data_1, ((2 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL0)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL0, test14

//---------------------------------------------------------------------------------------------------------------------------------
//                    4KB PAGE    Region 1 under test at level 0 -- RWX permissions given to the region
//---------------------------------------------------------------------------------------------------------------------------------

#ifdef S1P12P0_OR_LATER_SUPPORTED
  // Test case 15: Test in S-Mode | RWX bit set | PTE.PBMT=3 | expected = Store, Load & Instr page faults
  PTE_SETUP_SV57(rvtest_slvl3_pg_tbl, (PTE_V), va_data, LEVEL4)
  PTE_SETUP_SV57(rvtest_slvl2_pg_tbl, (PTE_V), va_data, LEVEL3)
  PTE_SETUP_SV57(rvtest_slvl1_pg_tbl, (PTE_V), va_data, LEVEL2)
  PTE_SETUP_SV57(rvtest_slvl0_pg_tbl, (PTE_V), va_data, LEVEL1)
  PTE_SETUP_SV57(rvtest_data_1, ((3 << 61) | PTE_D | PTE_A | PTE_X | PTE_W | PTE_R | PTE_V), va_data, LEVEL0)
  sfence.vma

  TEST_CASES_RUNNER Smode, va_data, LEVEL0, test15
#endif


//---------------------------------------------------------------------------------------------------------------------------------
RVTEST_CODE_END
RVTEST_DATA_BEGIN

//---------------------------------------------------------------------------------------------------------------------------------
//                                            PHYSICAL ADDRESS REGION FOR TESTING
//---------------------------------------------------------------------------------------------------------------------------------
// Physical Address region under testing for LEVEL 0, 1, 2, 3 and 4
.p2align 12
rvtest_data_1:
  nop
  addi a4, a2, 4
  jr ra
  nop
  .word 0xbeefcaf1          // Random word
  .word 0xbeefcaf2          // Random word
  nop
  jr ra

//---------------------------------------------------------------------------------------------------------------------------------

// Page Tables
.p2align 12
rvtest_slvl0_pg_tbl:
    .skip(4096)
rvtest_slvl1_pg_tbl:
    .skip(4096)
rvtest_slvl2_pg_tbl:
    .skip(4096)
rvtest_slvl3_pg_tbl:
    .skip(4096)

test1_store_str:  .string "\"Mismatch during sw in Test Case 1!\""
test1_load_str:   .string "\"Mismatch during lw in Test Case 1!\""
test1_exec_str:   .string "\"Mismatch during jalr in Test Case 1!\""
test2_store_str:  .string "\"Mismatch during sw in Test Case 2!\""
test2_load_str:   .string "\"Mismatch during lw in Test Case 2!\""
test2_exec_str:   .string "\"Mismatch during jalr in Test Case 2!\""
test3_store_str:  .string "\"Mismatch during sw in Test Case 3!\""
test3_load_str:   .string "\"Mismatch during lw in Test Case 3!\""
test3_exec_str:   .string "\"Mismatch during jalr in Test Case 3!\""
test4_store_str:  .string "\"Mismatch during sw in Test Case 4!\""
test4_load_str:   .string "\"Mismatch during lw in Test Case 4!\""
test4_exec_str:   .string "\"Mismatch during jalr in Test Case 4!\""
test5_store_str:  .string "\"Mismatch during sw in Test Case 5!\""
test5_load_str:   .string "\"Mismatch during lw in Test Case 5!\""
test5_exec_str:   .string "\"Mismatch during jalr in Test Case 5!\""
test6_store_str:  .string "\"Mismatch during sw in Test Case 6!\""
test6_load_str:   .string "\"Mismatch during lw in Test Case 6!\""
test6_exec_str:   .string "\"Mismatch during jalr in Test Case 6!\""
test7_store_str:  .string "\"Mismatch during sw in Test Case 7!\""
test7_load_str:   .string "\"Mismatch during lw in Test Case 7!\""
test7_exec_str:   .string "\"Mismatch during jalr in Test Case 7!\""
test8_store_str:  .string "\"Mismatch during sw in Test Case 8!\""
test8_load_str:   .string "\"Mismatch during lw in Test Case 8!\""
test8_exec_str:   .string "\"Mismatch during jalr in Test Case 8!\""
test9_store_str:  .string "\"Mismatch during sw in Test Case 9!\""
test9_load_str:   .string "\"Mismatch during lw in Test Case 9!\""
test9_exec_str:   .string "\"Mismatch during jalr in Test Case 9!\""
test10_store_str:  .string "\"Mismatch during sw in Test Case 10!\""
test10_load_str:   .string "\"Mismatch during lw in Test Case 10!\""
test10_exec_str:   .string "\"Mismatch during jalr in Test Case 10!\""
test11_store_str:  .string "\"Mismatch during sw in Test Case 11!\""
test11_load_str:   .string "\"Mismatch during lw in Test Case 11!\""
test11_exec_str:   .string "\"Mismatch during jalr in Test Case 11!\""
test12_store_str:  .string "\"Mismatch during sw in Test Case 12!\""
test12_load_str:   .string "\"Mismatch during lw in Test Case 12!\""
test12_exec_str:   .string "\"Mismatch during jalr in Test Case 12!\""
test13_store_str:  .string "\"Mismatch during sw in Test Case 13!\""
test13_load_str:   .string "\"Mismatch during lw in Test Case 13!\""
test13_exec_str:   .string "\"Mismatch during jalr in Test Case 13!\""
test14_store_str:  .string "\"Mismatch during sw in Test Case 14!\""
test14_load_str:   .string "\"Mismatch during lw in Test Case 14!\""
test14_exec_str:   .string "\"Mismatch during jalr in Test Case 14!\""
test15_store_str:  .string "\"Mismatch during sw in Test Case 15!\""
test15_load_str:   .string "\"Mismatch during lw in Test Case 15!\""
test15_exec_str:   .string "\"Mismatch during jalr in Test Case 15!\""

RVTEST_DATA_END
RVTEST_SIG_SETUP
