# SPDX-License-Identifier: Apache-2.0
# Jordan Carlin jcarlin@hmc.edu April 2026
# CI configuration for Spike simulator
# Shared across all Spike configs

ci_enabled: true
# Smstateen will be added back once sail starts supporting Sscsrind too
# Sdtrig* not yet supported in Sail reference
exclude_extensions: "Smstateen,SdtrigSm,SdtrigS,SdtrigU"
install_script: ".github/scripts/install-spike.sh"
apt_packages: "device-tree-compiler libboost-regex-dev libboost-system-dev"
shards: 1
config_shards:
  spike-rv64-max: 2
