///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zbkb_andn_cg = new(); Zbkb_andn_cg.set_inst_name("obj_Zbkb_andn");
    Zbkb_brev8_cg = new(); Zbkb_brev8_cg.set_inst_name("obj_Zbkb_brev8");
    Zbkb_orn_cg = new(); Zbkb_orn_cg.set_inst_name("obj_Zbkb_orn");
    Zbkb_pack_cg = new(); Zbkb_pack_cg.set_inst_name("obj_Zbkb_pack");
    Zbkb_packh_cg = new(); Zbkb_packh_cg.set_inst_name("obj_Zbkb_packh");
    Zbkb_rev8_cg = new(); Zbkb_rev8_cg.set_inst_name("obj_Zbkb_rev8");
    Zbkb_rol_cg = new(); Zbkb_rol_cg.set_inst_name("obj_Zbkb_rol");
    Zbkb_ror_cg = new(); Zbkb_ror_cg.set_inst_name("obj_Zbkb_ror");
    Zbkb_rori_cg = new(); Zbkb_rori_cg.set_inst_name("obj_Zbkb_rori");
    Zbkb_xnor_cg = new(); Zbkb_xnor_cg.set_inst_name("obj_Zbkb_xnor");
`ifdef UDB_MXLEN_32
    Zbkb_unzip_cg = new(); Zbkb_unzip_cg.set_inst_name("obj_Zbkb_unzip");
    Zbkb_zip_cg = new(); Zbkb_zip_cg.set_inst_name("obj_Zbkb_zip");
`endif
`ifdef UDB_MXLEN_64
    Zbkb_packw_cg = new(); Zbkb_packw_cg.set_inst_name("obj_Zbkb_packw");
    Zbkb_rolw_cg = new(); Zbkb_rolw_cg.set_inst_name("obj_Zbkb_rolw");
    Zbkb_roriw_cg = new(); Zbkb_roriw_cg.set_inst_name("obj_Zbkb_roriw");
    Zbkb_rorw_cg = new(); Zbkb_rorw_cg.set_inst_name("obj_Zbkb_rorw");
`endif
