///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZCF
`ifdef UDB_MXLEN_32
covergroup Zcf_c_flw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.flw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd_p : coverpoint ins.get_fpr_c_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_imm_mul : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:124]} with (item % 4 == 0);
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

endgroup
// ---------------------
covergroup Zcf_c_flwsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.flwsp"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_imm_mul_4sp : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:252]} with (item % 4 == 0);
    }

endgroup
// ---------------------
covergroup Zcf_c_fsw_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.fsw"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs2_p : coverpoint ins.get_fpr_c_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_imm_mul : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:124]} with (item % 4 == 0);
    }

    cp_rs1_p : coverpoint ins.get_gpr_c_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

endgroup
// ---------------------
covergroup Zcf_c_fswsp_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.fswsp"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_imm_mul_4sp : coverpoint ins.current.imm iff (ins.trap == 0) {
        // Immediate Multiples of 4
        bins offset[] = {[0:252]} with (item % 4 == 0);
    }

endgroup
// ---------------------
`endif
function void zcf_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
`ifdef UDB_MXLEN_32
        "c.flw"     : begin
            Zcf_c_flw_cg.sample(ins);
        end
        "c.flwsp"     : begin
            Zcf_c_flwsp_cg.sample(ins);
        end
        "c.fsw"     : begin
            Zcf_c_fsw_cg.sample(ins);
        end
        "c.fswsp"     : begin
            Zcf_c_fswsp_cg.sample(ins);
        end
`endif
    endcase
endfunction
