///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZCMOP
covergroup Zcmop_c_mop_1_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.1"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.1"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_11_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.11"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.11"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_13_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.13"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.13"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_15_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.15"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.15"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_3_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.3"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.3"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_5_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.5"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.5"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_7_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.7"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.7"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
covergroup Zcmop_c_mop_9_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "c.mop.9"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    // C.MOP.n is defined to not write any register.  The test seeds registers, executes the
    // instruction, and writes them to the signature, so the coverpoint just checks execution.

    cp_custom_mop_no_write : coverpoint ins.ins_str == "c.mop.9"  iff (ins.trap == 0 )  {
        bins no_write  = {1};
    }

endgroup
// ---------------------
function void zcmop_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "c.mop.1"     : begin
            Zcmop_c_mop_1_cg.sample(ins);
        end
        "c.mop.11"     : begin
            Zcmop_c_mop_11_cg.sample(ins);
        end
        "c.mop.13"     : begin
            Zcmop_c_mop_13_cg.sample(ins);
        end
        "c.mop.15"     : begin
            Zcmop_c_mop_15_cg.sample(ins);
        end
        "c.mop.3"     : begin
            Zcmop_c_mop_3_cg.sample(ins);
        end
        "c.mop.5"     : begin
            Zcmop_c_mop_5_cg.sample(ins);
        end
        "c.mop.7"     : begin
            Zcmop_c_mop_7_cg.sample(ins);
        end
        "c.mop.9"     : begin
            Zcmop_c_mop_9_cg.sample(ins);
        end
    endcase
endfunction
