///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZCMP
covergroup Zcmp_cm_mva01s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_zcmp_mva01s : coverpoint ins.current.insn[9:7] iff (ins.trap == 0) {
        bins s0 = {3'd0};
        bins s1 = {3'd1};
        bins s2 = {3'd2};
        bins s3 = {3'd3};
        bins s4 = {3'd4};
        bins s5 = {3'd5};
        bins s6 = {3'd6};
        bins s7 = {3'd7};
    }

endgroup
// ---------------------
covergroup Zcmp_cm_mvsa01_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_zcmp_mvsa01 : coverpoint ins.current.insn[9:7] iff (ins.trap == 0) {
        bins s0 = {3'd0};
        bins s1 = {3'd1};
        bins s2 = {3'd2};
        bins s3 = {3'd3};
        bins s4 = {3'd4};
        bins s5 = {3'd5};
        bins s6 = {3'd6};
        bins s7 = {3'd7};
    }

endgroup
// ---------------------
covergroup Zcmp_cm_pop_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_zcmp_pop_rlist : coverpoint ins.current.insn[7:4] iff (ins.trap == 0) {
        bins rlist4  = {4'd4};
        bins rlist5  = {4'd5};
        bins rlist6  = {4'd6};
        bins rlist7  = {4'd7};
        bins rlist8  = {4'd8};
        bins rlist9  = {4'd9};
        bins rlist10 = {4'd10};
        bins rlist11 = {4'd11};
        bins rlist12 = {4'd12};
        bins rlist13 = {4'd13};
        bins rlist14 = {4'd14};
        bins rlist15 = {4'd15};
    }

endgroup
// ---------------------
covergroup Zcmp_cm_popret_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_zcmp_popret_rlist : coverpoint ins.current.insn[7:4] iff (ins.trap == 0) {
        bins rlist4  = {4'd4};
        bins rlist5  = {4'd5};
        bins rlist6  = {4'd6};
        bins rlist7  = {4'd7};
        bins rlist8  = {4'd8};
        bins rlist9  = {4'd9};
        bins rlist10 = {4'd10};
        bins rlist11 = {4'd11};
        bins rlist12 = {4'd12};
        bins rlist13 = {4'd13};
        bins rlist14 = {4'd14};
        bins rlist15 = {4'd15};
    }

endgroup
// ---------------------
covergroup Zcmp_cm_popretz_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_zcmp_popretz_rlist : coverpoint ins.current.insn[7:4] iff (ins.trap == 0) {
        bins rlist4  = {4'd4};
        bins rlist5  = {4'd5};
        bins rlist6  = {4'd6};
        bins rlist7  = {4'd7};
        bins rlist8  = {4'd8};
        bins rlist9  = {4'd9};
        bins rlist10 = {4'd10};
        bins rlist11 = {4'd11};
        bins rlist12 = {4'd12};
        bins rlist13 = {4'd13};
        bins rlist14 = {4'd14};
        bins rlist15 = {4'd15};
    }

endgroup
// ---------------------
covergroup Zcmp_cm_push_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_zcmp_push_rlist : coverpoint ins.current.insn[7:4] iff (ins.trap == 0) {
        bins rlist4  = {4'd4};
        bins rlist5  = {4'd5};
        bins rlist6  = {4'd6};
        bins rlist7  = {4'd7};
        bins rlist8  = {4'd8};
        bins rlist9  = {4'd9};
        bins rlist10 = {4'd10};
        bins rlist11 = {4'd11};
        bins rlist12 = {4'd12};
        bins rlist13 = {4'd13};
        bins rlist14 = {4'd14};
        bins rlist15 = {4'd15};
    }

endgroup
// ---------------------
function void zcmp_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "cm.mva01s"     : begin
            Zcmp_cm_mva01s_cg.sample(ins);
        end
        "cm.mvsa01"     : begin
            Zcmp_cm_mvsa01_cg.sample(ins);
        end
        "cm.pop"     : begin
            Zcmp_cm_pop_cg.sample(ins);
        end
        "cm.popret"     : begin
            Zcmp_cm_popret_cg.sample(ins);
        end
        "cm.popretz"     : begin
            Zcmp_cm_popretz_cg.sample(ins);
        end
        "cm.push"     : begin
            Zcmp_cm_push_cg.sample(ins);
        end
    endcase
endfunction
