///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zcmp_cm_mva01s_cg = new(); Zcmp_cm_mva01s_cg.set_inst_name("obj_Zcmp_cm_mva01s");
    Zcmp_cm_mvsa01_cg = new(); Zcmp_cm_mvsa01_cg.set_inst_name("obj_Zcmp_cm_mvsa01");
    Zcmp_cm_pop_cg = new(); Zcmp_cm_pop_cg.set_inst_name("obj_Zcmp_cm_pop");
    Zcmp_cm_popret_cg = new(); Zcmp_cm_popret_cg.set_inst_name("obj_Zcmp_cm_popret");
    Zcmp_cm_popretz_cg = new(); Zcmp_cm_popretz_cg.set_inst_name("obj_Zcmp_cm_popretz");
    Zcmp_cm_push_cg = new(); Zcmp_cm_push_cg.set_inst_name("obj_Zcmp_cm_push");
