///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFAZFHD
covergroup ZfaZfhD_fleq_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfaZfhD_fli_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfaZfhD_fltq_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfaZfhD_fmaxm_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfaZfhD_fminm_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfaZfhD_fround_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfaZfhD_froundnx_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
function void zfazfhd_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fleq.h"     : begin
            ZfaZfhD_fleq_h_cg.sample(ins);
        end
        "fli.h"     : begin
            ZfaZfhD_fli_h_cg.sample(ins);
        end
        "fltq.h"     : begin
            ZfaZfhD_fltq_h_cg.sample(ins);
        end
        "fmaxm.h"     : begin
            ZfaZfhD_fmaxm_h_cg.sample(ins);
        end
        "fminm.h"     : begin
            ZfaZfhD_fminm_h_cg.sample(ins);
        end
        "fround.h"     : begin
            ZfaZfhD_fround_h_cg.sample(ins);
        end
        "froundnx.h"     : begin
            ZfaZfhD_froundnx_h_cg.sample(ins);
        end
    endcase
endfunction
