///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFBFMIN
covergroup Zfbfmin_fcvt_bf16_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.bf16.s"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_voun : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
        wildcard bins OF   = (5'b??0?? => 5'b??1??);
        wildcard bins OF1  = (5'b??1?? => 5'b??1??);
        wildcard bins UF   = (5'b???0? => 5'b???1?);
        wildcard bins UF1  = (5'b???1? => 5'b???1?);
        wildcard bins NX   = (5'b????0 => 5'b????1);
        wildcard bins NX1  = (5'b????1 => 5'b????1);
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // FS1 edges
        bins pos0             = {32'h00000000};
        bins neg0             = {32'h80000000};
        bins pos1             = {32'h3f800000};
        bins neg1             = {32'hbf800000};
        bins pos1p5           = {32'h3fc00000};
        bins neg1p5           = {32'hbfc00000};
        bins pos2             = {32'h40000000};
        bins neg2             = {32'hc0000000};
        bins posminnorm       = {32'h00800000};
        bins negminnorm       = {32'h80800000};
        bins posmaxnorm       = {32'h7f7fffff};
        bins negmaxnorm       = {32'hff7fffff};
        bins posmax_subnorm   = {32'h007fffff};
        bins negmax_subnorm   = {32'h807fffff};
        bins posmid_subnorm   = {32'h00400000};
        bins negmid_subnorm   = {32'h80400000};
        bins posmin_subnorm   = {32'h00000001};
        bins negmin_subnorm   = {32'h80000001};
        bins posinfinity      = {32'h7f800000};
        bins neginfinity      = {32'hff800000};
        bins posQNaN          = {[32'h7fc00000:32'h7fffffff]};
        bins posSNaN          = {[32'h7f800001:32'h7fbfffff]};
        bins negQNaN          = {[32'hffc00000:32'hffffffff]};
        bins negSNaN          = {[32'hff800001:32'hffbfffff]};
        bins posrandom        = {32'h7ef8654f};
        bins negrandom        = {32'h813d9ab0};
    }

endgroup
// ---------------------
covergroup Zfbfmin_fcvt_s_bf16_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.s.bf16"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_BF16 : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges
        bins pos0             = {32'h0000};
        bins neg0             = {32'h8000};
        bins pos1             = {32'h3f80};
        bins neg1             = {32'hbf80};
        bins pos1p5           = {32'h3fc0};
        bins neg1p5           = {32'hbfc0};
        bins pos2             = {32'h4000};
        bins neg2             = {32'hc000};
        bins posminnorm       = {32'h0080};
        bins negminnorm       = {32'h8080};
        bins posmaxnorm       = {32'h7f7f};
        bins negmaxnorm       = {32'hff7f};
        bins posmax_subnorm   = {32'h007f};
        bins negmax_subnorm   = {32'h807f};
        bins posmid_subnorm   = {32'h0040};
        bins negmid_subnorm   = {32'h8040};
        bins posmin_subnorm   = {32'h0001};
        bins negmin_subnorm   = {32'h8001};
        bins posinfinity      = {32'h7f80};
        bins neginfinity      = {32'hff80};
        bins posQNaN          = {[32'h7fc0:32'h7fff]};
        bins posSNaN          = {[32'h7f81:32'h7fbf]};
        bins negQNaN          = {[32'hffc0:32'hffff]};
        bins negSNaN          = {[32'hff81:32'hffbf]};
        bins posrandom        = {32'h7ef8};
        bins negrandom        = {32'h813d};
    }

endgroup
// ---------------------
covergroup Zfbfmin_flh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "flh"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_imm_edges : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins zero  = {0};
        bins p0    = {1};
        bins p1    = {2};
        bins three = {3};
        bins p2    = {4};
        bins p3    = {8};
        bins p4    = {16};
        bins p5    = {32};
        bins p6    = {64};
        bins p7    = {128};
        bins p8    = {256};
        bins p9    = {512};
        bins hm1   = {1023};
        bins p10   = {1024};
        bins max   = {2047};
        bins min   = {-2048};
        bins minp1 = {-2047};
        bins onesm1 = {-2};
        bins ones   = {-1};
        bins randomp = {1795};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
covergroup Zfbfmin_fmv_h_x_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fmv.h.x"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_rs1 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

endgroup
// ---------------------
covergroup Zfbfmin_fmv_x_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fmv.x.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

endgroup
// ---------------------
covergroup Zfbfmin_fsh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fsh"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_badNB_S_H : coverpoint unsigned'(ins.current.fs2_val[31:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs2_edges_H : coverpoint unsigned'(ins.current.fs2_val[15:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_imm_edges : coverpoint signed'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins zero  = {0};
        bins p0    = {1};
        bins p1    = {2};
        bins three = {3};
        bins p2    = {4};
        bins p3    = {8};
        bins p4    = {16};
        bins p5    = {32};
        bins p6    = {64};
        bins p7    = {128};
        bins p8    = {256};
        bins p9    = {512};
        bins hm1   = {1023};
        bins p10   = {1024};
        bins max   = {2047};
        bins min   = {-2048};
        bins minp1 = {-2047};
        bins onesm1 = {-2};
        bins ones   = {-1};
        bins randomp = {1795};
    }

    cp_rs1_nx0 : coverpoint ins.get_gpr_reg(ins.current.rs1) iff (ins.trap == 0) {
        // RS1 register assignment (excluding x0)
        ignore_bins x0 = {x0};
    }

endgroup
// ---------------------
function void zfbfmin_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fcvt.bf16.s"     : begin
            Zfbfmin_fcvt_bf16_s_cg.sample(ins);
        end
        "fcvt.s.bf16"     : begin
            Zfbfmin_fcvt_s_bf16_cg.sample(ins);
        end
        "flh"     : begin
            Zfbfmin_flh_cg.sample(ins);
        end
        "fmv.h.x"     : begin
            Zfbfmin_fmv_h_x_cg.sample(ins);
        end
        "fmv.x.h"     : begin
            Zfbfmin_fmv_x_h_cg.sample(ins);
        end
        "fsh"     : begin
            Zfbfmin_fsh_cg.sample(ins);
        end
    endcase
endfunction
