///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZICNTR
covergroup Zicntr_csrrc_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_cntr : coverpoint ins.current.insn[31:20] iff (ins.get_gpr_reg(ins.current.rs1) == x0) {
        bins csr_cycle   = {12'hC00};
        bins csr_time    = {12'hC01};
        bins csr_instret = {12'hC02};
        `ifdef UDB_MXLEN_32
                bins csr_cycleh   = {12'hC80};
                bins csr_timeh    = {12'hC81};
                bins csr_instreth = {12'hC82};
        `endif
    }

endgroup
// ---------------------
covergroup Zicntr_csrrs_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_cntr : coverpoint ins.current.insn[31:20] iff (ins.get_gpr_reg(ins.current.rs1) == x0) {
        bins csr_cycle   = {12'hC00};
        bins csr_time    = {12'hC01};
        bins csr_instret = {12'hC02};
        `ifdef UDB_MXLEN_32
                bins csr_cycleh   = {12'hC80};
                bins csr_timeh    = {12'hC81};
                bins csr_instreth = {12'hC82};
        `endif
    }

endgroup
// ---------------------
function void zicntr_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "csrrc"     : begin
            Zicntr_csrrc_cg.sample(ins);
        end
        "csrrs"     : begin
            Zicntr_csrrs_cg.sample(ins);
        end
    endcase
endfunction
