///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zilx_lxh_cg = new(); Zilx_lxh_cg.set_inst_name("obj_Zilx_lxh");
    Zilx_lxhu_cg = new(); Zilx_lxhu_cg.set_inst_name("obj_Zilx_lxhu");
    Zilx_lxsb_cg = new(); Zilx_lxsb_cg.set_inst_name("obj_Zilx_lxsb");
    Zilx_lxsbu_cg = new(); Zilx_lxsbu_cg.set_inst_name("obj_Zilx_lxsbu");
    Zilx_lxsh_cg = new(); Zilx_lxsh_cg.set_inst_name("obj_Zilx_lxsh");
    Zilx_lxshu_cg = new(); Zilx_lxshu_cg.set_inst_name("obj_Zilx_lxshu");
    Zilx_lxsw_cg = new(); Zilx_lxsw_cg.set_inst_name("obj_Zilx_lxsw");
    Zilx_lxw_cg = new(); Zilx_lxw_cg.set_inst_name("obj_Zilx_lxw");
`ifdef UDB_MXLEN_64
    Zilx_lxd_cg = new(); Zilx_lxd_cg.set_inst_name("obj_Zilx_lxd");
    Zilx_lxsd_cg = new(); Zilx_lxsd_cg.set_inst_name("obj_Zilx_lxsd");
    Zilx_lxsuwb_cg = new(); Zilx_lxsuwb_cg.set_inst_name("obj_Zilx_lxsuwb");
    Zilx_lxsuwbu_cg = new(); Zilx_lxsuwbu_cg.set_inst_name("obj_Zilx_lxsuwbu");
    Zilx_lxsuwd_cg = new(); Zilx_lxsuwd_cg.set_inst_name("obj_Zilx_lxsuwd");
    Zilx_lxsuwh_cg = new(); Zilx_lxsuwh_cg.set_inst_name("obj_Zilx_lxsuwh");
    Zilx_lxsuwhu_cg = new(); Zilx_lxsuwhu_cg.set_inst_name("obj_Zilx_lxsuwhu");
    Zilx_lxsuww_cg = new(); Zilx_lxsuww_cg.set_inst_name("obj_Zilx_lxsuww");
    Zilx_lxsuwwu_cg = new(); Zilx_lxsuwwu_cg.set_inst_name("obj_Zilx_lxsuwwu");
    Zilx_lxswu_cg = new(); Zilx_lxswu_cg.set_inst_name("obj_Zilx_lxswu");
    Zilx_lxwu_cg = new(); Zilx_lxwu_cg.set_inst_name("obj_Zilx_lxwu");
`endif
