# SPDX-License-Identifier: Apache-2.0
# Jordan Carlin jcarlin@hmc.edu April 2026
# CI configuration for Whisper simulator

# SsstrictSm, SsstrictS, SsstrictU excluded because of sail-riscv#1882, sail-riscv#1880
#   Should be fixed in Sail 0.14
# Smstateen Sail does not yet support 1P13 bit
# ExceptionsSvZalrsc: Whisper reports page faults where Sail expects access faults.
# Sdtrig* not yet implemented in Sail
ci_enabled: true
exclude_extensions: "SsstrictSm,SsstrictS,SsstrictU,ExceptionsSvZalrsc,Smstateen,SdtrigSm,SdtrigS,SdtrigU"
exclude_configs:
  - whisper-rv32-max-spike-ref
  - whisper-rv64-max-spike-ref
install_script: ".github/scripts/install-whisper.sh"
apt_packages: "libboost-program-options-dev"
shards: 1
config_shards:
  whisper-rv64-max: 2
