name: visionfive2-rv64gc
compiler_exe: riscv64-unknown-elf-gcc # executable name on $PATH or full path to executable
objdump_exe: riscv64-unknown-elf-objdump # executable name on $PATH or full path to executable, optional
ref_model_exe: /opt/sail-riscv/bin/sail_riscv_sim  # executable name on $PATH or full path to executable
udb_config: visionfive2-rv64gc.yaml
linker_script: link.ld
dut_include_dir: . # Directory containing DUT specific rvmodel_macros.h header/

