name: Build image

on:
  workflow_dispatch:
  push:
    branches:
      - act4
    tags-ignore:
      - cert-docs-*

jobs:
  act4-build-image:
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1.17.0
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: true
      cache: true
      cache-mode: max
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository_owner }}/act4-build
      meta-tags: |
        type=ref,event=tag
        type=ref,event=branch
        type=sha,format=long
      meta-flavor: |
        latest=${{ github.ref == 'refs/heads/act4' }}
      target: act4-build
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  act4-image:
    needs: act4-build-image
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1.17.0
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: true
      cache: true
      cache-mode: min
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository_owner }}/act4
      meta-tags: |
        type=ref,event=tag
        type=ref,event=branch
        type=sha,format=long
      meta-flavor: |
        latest=false
      target: act4
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.ref != 'refs/heads/act4' }}
